import {
  Zap,
  CalendarDays,
  Slack,
  Upload,
  Bot,
  MessageSquare,
  Brain,
  Code,
  TestTube,
  Search,
  Database,
  FileText,
  Globe,
  Sparkles,
  Network,
  Mail,
  Github,
  Users,
  Shield,
  AlertTriangle,
  Lock,
  Activity,
  BarChart3,
  Star,
  Share2,
} from "lucide-react";
import type { NodeType } from "@/modules/laboratory3/agents/components/NodePalette";

export const labCategoryTitles: Record<string, string> = {
  triggers: "ТРИГГЕРЫ",
  llm: "LLM / CHAT",
  knowledge: "ЗНАНИЯ",
  tools: "ИНСТРУМЕНТЫ",
  memory: "ПАМЯТЬ",
  guardrails: "БЕЗОПАСНОСТЬ",
  eval: "МОНИТОРИНГ",
  actions: "ДЕЙСТВИЯ",
};

export const labNodeLibrary: NodeType[] = [
  // ТРИГГЕРЫ
  {
    type: "trigger",
    category: "triggers",
    label: "Webhook",
    icon: Zap,
    color: "bg-blue-500",
    description: "HTTP триггер",
    config: { method: "POST", path: "/webhook" },
  },
  {
    type: "trigger",
    category: "triggers",
    label: "Расписание",
    icon: CalendarDays,
    color: "bg-green-500",
    description: "Cron триггер",
    config: { scheduleType: "cron", cronExpression: "0 0 * * *" },
  },
  {
    type: "trigger",
    category: "triggers",
    label: "Slack Events",
    icon: Slack,
    color: "bg-purple-500",
    description: "События Slack",
    config: { eventType: "slack" },
  },
  {
    type: "trigger",
    category: "triggers",
    label: "File Upload",
    icon: Upload,
    color: "bg-orange-500",
    description: "Загрузка файла",
    config: { accept: ".pdf,.csv,.docx" },
  },
  {
    type: "trigger",
    category: "triggers",
    label: "Dashboard Button",
    icon: Bot,
    color: "bg-teal-500",
    description: "Кнопка дашборда",
    config: { label: "Запустить" },
  },
  // LLM / CHAT
  {
    type: "llm",
    category: "llm",
    label: "Chat GPT",
    icon: MessageSquare,
    color: "bg-indigo-500",
    description: "OpenAI модель",
    config: { model: "gpt-4o", provider: "openai" },
  },
  {
    type: "llm",
    category: "llm",
    label: "Claude",
    icon: MessageSquare,
    color: "bg-violet-500",
    description: "Anthropic модель",
    config: { model: "claude-sonnet-4", provider: "anthropic" },
  },
  {
    type: "llm",
    category: "llm",
    label: "Gemini",
    icon: Brain,
    color: "bg-blue-500",
    description: "Google модель",
    config: { model: "gemini-pro", provider: "google" },
  },
  {
    type: "llm",
    category: "llm",
    label: "System Prompt",
    icon: Code,
    color: "bg-pink-500",
    description: "Системный промпт",
    config: { prompt: "" },
  },
  {
    type: "llm",
    category: "llm",
    label: "Few-shot",
    icon: TestTube,
    color: "bg-teal-500",
    description: "Примеры",
    config: { examples: [] },
  },
  // ЗНАНИЯ
  {
    type: "knowledge",
    category: "knowledge",
    label: "RAG Search",
    icon: Search,
    color: "bg-lime-500",
    description: "Поиск по базе",
    config: { topK: 5 },
  },
  {
    type: "knowledge",
    category: "knowledge",
    label: "Vector DB",
    icon: Database,
    color: "bg-cyan-500",
    description: "Векторная БД",
    config: { provider: "pinecone" },
  },
  {
    type: "knowledge",
    category: "knowledge",
    label: "Document",
    icon: FileText,
    color: "bg-yellow-500",
    description: "Документы",
    config: { format: "pdf" },
  },
  {
    type: "knowledge",
    category: "knowledge",
    label: "Web Scraper",
    icon: Globe,
    color: "bg-sky-500",
    description: "Веб парсер",
    config: { url: "" },
  },
  {
    type: "knowledge",
    category: "knowledge",
    label: "Embeddings",
    icon: Sparkles,
    color: "bg-emerald-500",
    description: "Векторизация",
    config: { model: "text-embedding-3-small" },
  },
  // ИНСТРУМЕНТЫ
  {
    type: "tool",
    category: "tools",
    label: "HTTP Request",
    icon: Network,
    color: "bg-purple-500",
    description: "API запрос",
    config: { method: "GET", url: "" },
  },
  {
    type: "tool",
    category: "tools",
    label: "SQL Query",
    icon: Database,
    color: "bg-orange-500",
    description: "SQL запрос",
    config: { database: "postgresql", query: "" },
  },
  {
    type: "tool",
    category: "tools",
    label: "Python Script",
    icon: Code,
    color: "bg-pink-500",
    description: "Python код",
    config: { code: "" },
  },
  {
    type: "tool",
    category: "tools",
    label: "Email",
    icon: Mail,
    color: "bg-red-500",
    description: "Отправка почты",
    config: { action: "send" },
  },
  {
    type: "tool",
    category: "tools",
    label: "Git Actions",
    icon: Github,
    color: "bg-gray-600",
    description: "Git операции",
    config: { action: "push" },
  },
  // ПАМЯТЬ
  {
    type: "memory",
    category: "memory",
    label: "Short Memory",
    icon: Brain,
    color: "bg-blue-400",
    description: "Краткосрочная",
    config: { ttl: 3600 },
  },
  {
    type: "memory",
    category: "memory",
    label: "Long Memory",
    icon: Database,
    color: "bg-blue-600",
    description: "Долгосрочная",
    config: { retention: "30d" },
  },
  {
    type: "memory",
    category: "memory",
    label: "Session Store",
    icon: Users,
    color: "bg-indigo-500",
    description: "Сессия",
    config: { store: "redis" },
  },
  // БЕЗОПАСНОСТЬ
  {
    type: "guardrail",
    category: "guardrails",
    label: "PII Masking",
    icon: Shield,
    color: "bg-red-600",
    description: "Маскировка данных",
    config: { action: "mask" },
  },
  {
    type: "guardrail",
    category: "guardrails",
    label: "Content Filter",
    icon: AlertTriangle,
    color: "bg-orange-600",
    description: "Фильтр контента",
    config: { threshold: 0.8 },
  },
  {
    type: "guardrail",
    category: "guardrails",
    label: "Rate Limits",
    icon: Lock,
    color: "bg-yellow-600",
    description: "Лимиты запросов",
    config: { maxRequests: 100, window: "1h" },
  },
  // МОНИТОРИНГ
  {
    type: "eval",
    category: "eval",
    label: "Logging",
    icon: Activity,
    color: "bg-green-600",
    description: "Логирование",
    config: { level: "info" },
  },
  {
    type: "eval",
    category: "eval",
    label: "Metrics",
    icon: BarChart3,
    color: "bg-purple-600",
    description: "Метрики",
    config: { metrics: ["latency", "error_rate"] },
  },
  {
    type: "eval",
    category: "eval",
    label: "Feedback",
    icon: Star,
    color: "bg-teal-600",
    description: "Обратная связь",
    config: { questions: ["Было полезно?"] },
  },
  // ДЕЙСТВИЯ
  {
    type: "action",
    category: "actions",
    label: "REST API",
    icon: Globe,
    color: "bg-indigo-600",
    description: "REST эндпоинт",
    config: { path: "/api/workflow", method: "POST" },
  },
  {
    type: "action",
    category: "actions",
    label: "Chat Widget",
    icon: MessageSquare,
    color: "bg-teal-600",
    description: "Виджет чата",
    config: { theme: "light" },
  },
  {
    type: "action",
    category: "actions",
    label: "Slack Bot",
    icon: Slack,
    color: "bg-purple-600",
    description: "Slack бот",
    config: { channel: "" },
  },
  {
    type: "action",
    category: "actions",
    label: "Webhook Out",
    icon: Share2,
    color: "bg-blue-600",
    description: "Исходящий вебхук",
    config: { url: "" },
  },
];
